### PR TITLE
Add p11tool tests

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
This should work, one p11tool is part of the docker containers.

### CODE REVIEW

**Comment by williamcroberts** [comment]
I'll go update all the containers...
```
configure: error: Integration tests enabled but p11tool executable not found.
```

**Comment by AndreasFuchsSIT** [comment]
- Ubuntu works (errors come from nss test)
- OpenSuSE: p11tool works, but openssl fails
- Fedora: p11tool does not find our software token

This is soooo frustrating...
Anyone with access to OpenSuSE and/or Fedora who could trace this down a little ?

**Comment by williamcroberts** [comment]
> Anyone with access to OpenSuSE and/or Fedora who could trace this down a little ?

Welcome to the club! The flakyness of all this pkcs11 stuff is just so fun. I just enter the containers and debug by hand.

**Comment by dnoliver** [comment]
Fedora user here:

1. Fedora: p11tool does not find our software token

It happened before to me because of 2 reasons:
1. there was a missing module definition in /usr/share/p11-kit/modules/tpm2_pkcs11.module
2. there was an error in the lib (like this https://github.com/tpm2-software/tpm2-pkcs11/pull/458#issuecomment-601478159) and p11-kit ignored the module

hope it helps

**Comment by AndreasFuchsSIT** [comment]
Thanks for the help.
I'd expect to not go through p11kit but to access the token directly from p11tool.
That's how it works on opensuse-leap: https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/665831370?utm_medium=notification&utm_source=github_status
Suse also shows 2 p11kit modules but then tpm2-pkcs11 as a third module.
On F30 there's only 2 p11kit modules.

Any idea what the difference between suse and f30 is ?

**Comment by AndreasFuchsSIT** [comment]
p11tool on ubuntu searches for configs in $HOME/.config/pkcs11/modules
@dnoliver Do you know where p11tool searches on F30 ?

**Comment by dnoliver** [comment]
This are the paths I have in my Fedora 31

```bash
/root/.tpm2_pkcs11
/root/.tpm2_pkcs11/tpm2_pkcs11.sqlite3
/usr/lib64/pkcs11/libtpm2_pkcs11.so.0
/usr/lib64/pkcs11/libtpm2_pkcs11.so
/usr/lib64/pkcs11/libtpm2_pkcs11.so.0.0.0
/usr/lib64/pkcs11/libtpm2_pkcs11.la
/usr/share/p11-kit/modules/tpm2_pkcs11.module
/usr/local/lib/python3.7/site-packages/tpm2_pkcs11_tools-1.33.7-py3.7.egg
```

Config is in `/usr/share` and lib installed in `/usr/lib64/pkcs11`.

This works for me

```bash
export TPM2TOOLS_TCTI="device:/dev/tpmrm0"
export TPM2_PKCS11_TCTI="device:/dev/tpmrm0"
export TPM2_PKCS11_LOG_LEVEL=2

tpm2_clear
rm tpm2_pkcs11.sqlite3
tpm2_ptool init
tpm2_ptool addtoken --pid=1 --sopin=mysopin --userpin=myuserpin --label=label
tpm2_ptool addkey --algorithm=rsa2048 --label=label --userpin=myuserpin
tpm2_ptool config --key tcti --value "device:/dev/tpmrm0" --label label
p11-kit list-modules
TOKEN=$(p11tool --list-token-urls | grep "token=label")
export GNUTLS_PIN=myuserpin
export GNUTLS_SO_PIN=mysopin
p11tool --login --list-all "${TOKEN}" --outfile p11tool.out
```

**Comment by AndreasFuchsSIT** [comment]
Would you mind giving me the output of your `p11tool -d 9999 --list-tokens` and `p11tool -d 9999 --list-token-urls` ?

**Comment by dnoliver** [comment]
```bash
[root@fedora-server ~]# p11tool -d 9999 --list-tokens
Setting log level to 9999
WARNING:tcti:src/tss2-tcti/tcti-device.c:182:tcti_device_receive() The underlying IPC mechanism does not support asynchronous I/O. The 'timeout' parameter must be TSS2_TCTI_TIMEOUT_BLOCK 
ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:307:Esys_GetCapability_Finish() Received a non-TPM Error 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:245:Fapi_Initialize_Finish() Get capability data. ErrorCode (0x000a000b) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
|<2>| p11: Initializing module: p11-kit-trust
|<2>| p11: Initializing module: opensc
|<2>| p11: Initializing module: tpm2_pkcs11
|<3>| ASSERT: pkcs11.c[compat_load]:894
|<2>| p11: No login requested.
Token 0:
	URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
	Label: System Trust
|<2>| p11: No login requested.
	Type: Trust module
	Flags: uPIN uninitialized
	Manufacturer: PKCS#11 Kit
	Model: p11-kit-trust
	Serial: 1
|<2>| p11: No login requested.
	Module: p11-kit-trust.so


|<2>| p11: No login requested.
|<2>| p11: No login requested.
Token 1:
	URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
	Label: Default Trust
|<2>| p11: No login requested.
	Type: Trust module
	Flags: uPIN uninitialized
	Manufacturer: PKCS#11 Kit
	Model: p11-kit-trust
	Serial: 1
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
	Module: p11-kit-trust.so


|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
Token 2:
	URL: pkcs11:model=Intel;manufacturer=Intel;serial=0000000000000000;token=label
	Label: label
|<2>| p11: No login requested.
	Type: Hardware token
	Flags: RNG, Requires login
	Manufacturer: Intel
	Model: Intel
	Serial: 0000000000000000
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
	Module: libtpm2_pkcs11.so


|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
Token 3:
	URL: pkcs11:model=Intel;manufacturer=Intel;serial=0000000000000000;token=
	Label: 
|<2>| p11: No login requested.
	Type: Hardware token
	Flags: RNG, Requires login, Uninitialized, uPIN uninitialized
	Manufacturer: Intel
	Model: Intel
	Serial: 0000000000000000
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_modname_cb]:2368
|<2>| p11: No login requested.
	Module: libtpm2_pkcs11.so


|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_num_cb]:2334
|<3>| ASSERT: pkcs11.c[_gnutls_pkcs11_token_get_url]:2418
```

```bash
Setting log level to 9999
WARNING:tcti:src/tss2-tcti/tcti-device.c:182:tcti_device_receive() The underlying IPC mechanism does not support asynchronous I/O. The 'timeout' parameter must be TSS2_TCTI_TIMEOUT_BLOCK 
ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:307:Esys_GetCapability_Finish() Received a non-TPM Error 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:245:Fapi_Initialize_Finish() Get capability data. ErrorCode (0x000a000b) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001c4) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
WARNING:esys:src/tss2-esys/api/Esys_TestParms.c:269:Esys_TestParms_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_TestParms.c:95:Esys_TestParms() Esys Finish ErrorCode (0x000001e6) 
|<2>| p11: Initializing module: p11-kit-trust
|<2>| p11: Initializing module: opensc
|<2>| p11: Initializing module: tpm2_pkcs11
|<3>| ASSERT: pkcs11.c[compat_load]:894
|<2>| p11: No login requested.
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
|<2>| p11: No login requested.
|<2>| p11: No login requested.
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
pkcs11:model=Intel;manufacturer=Intel;serial=0000000000000000;token=label
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
pkcs11:model=Intel;manufacturer=Intel;serial=0000000000000000;token=
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<2>| p11: No login requested.
|<3>| ASSERT: pkcs11.c[find_token_num_cb]:2334
|<3>| ASSERT: pkcs11.c[_gnutls_pkcs11_token_get_url]:241
```

**Comment by AndreasFuchsSIT** [comment]
hmmm... you get a `p11: Initializing module: tpm2_pkcs11` but on CI I don't get it.
Hmpf....

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts The error is a nss-test error on fedora-30. The p11tool now works.

**Comment by williamcroberts** [comment]
> @williamcroberts The error is a nss-test error on fedora-30. The p11tool now works.

Maybe I was looking at to old of a build. Can you rebase ontop of master and force push?
I commented out that failure in the nss tools. For some reason, looking up by email address can cause it to grab the wrong token. All the commands that take the token name as well, work.

That should fix all these issues, and retrigger the builds.

**Comment by williamcroberts** [comment]
Except now there is this.. yeah!
https://github.com/tpm2-software/tpm2-pkcs11/issues/464

**Comment by AndreasFuchsSIT** [comment]
Yep, I am on top of master... ;-)

**Comment by williamcroberts** [comment]
Dang nss tests failed on Fedora 30, restarted them.

**Comment by AndreasFuchsSIT** [comment]
The only idea I'd have is that I'm configuring the module in /etc now, since p11tool does not support setting via $HOME anymore.
When you're testing, that may be an indicator.

**Comment by williamcroberts** [comment]
> The only idea I'd have is that I'm configuring the module in /etc now, since p11tool does not support setting via $HOME anymore.
> When you're testing, that may be an indicator.

@AndreasFuchsSIT @dkobras figured it out on PR https://github.com/tpm2-software/tpm2-pkcs11/pull/463

I'm just gonna pull yours in, as the failing test ins't your test. If for some reason master isn't passing, we'll just deal with it then.

**Pull request merged**
