### PR TITLE
Fix Buffer Size for ECDSA

### PR DESCRIPTION
**Pull request by PeterHuewe**
The function ec_fixup_size was not implemented correctly,
as the initial logic whether the fixup should be applied was inverted.
Moreover the function was only called if do_hash was set to true,
which is not the case for 'raw' ECDSA.

Fixes: 62a521d4964c8af03d886920be52047b4d60fe44
Fixes: #201

Signed-off-by: Peter Huewe <peter.huewe@infineon.com>

### CODE REVIEW

**Comment by PeterHuewe** [comment]
I'll look into why the tests fail....

**Comment by williamcroberts** [comment]
> I'll look into why the tests fail....

Probably add a regression test too. We need to get in the habit of adding a test when we fix a bug.

**Comment by PeterHuewe** [comment]
Same problem as always.
if (rv) vs if(!ptr) ....

**Comment by williamcroberts** [comment]
> Same problem as always.
> if (rv) vs if(!ptr) ....

I've done that myself, many times.

**Comment by PeterHuewe** [comment]
> 
> 
> > Same problem as always.
> > if (rv) vs if(!ptr) ....
>> if (rv) vs if(!ptr) ....
> 
> I've done that myself, many times.

That's why I prefer the explicit version for regular return codes.

**Comment by williamcroberts** [comment]
> > > Same problem as always.
> > > if (rv) vs if(!ptr) ....
> > > if (rv) vs if(!ptr) ....
> > 
> > 
> > I've done that myself, many times.
> 
> That's why I prefer the explicit version for regular return codes.

Why'd you change it from:
https://github.com/tpm2-software/tpm2-pkcs11/pull/239/files#diff-c3df73929e97a82485422329ed256f2cL563
```C
            tmp = ec_fixup_size(opdata->mtype, opdata->tobj, signature_len);
            if (tmp != CKR_OK) {
```

**Comment by PeterHuewe** [comment]
> 
> 
> > > > Same problem as always.
> > > > if (rv) vs if(!ptr) ....
> > > > if (rv) vs if(!ptr) ....
> > > 
> > > 
> > > I've done that myself, many times.
> > 
> > 
> > That's why I prefer the explicit version for regular return codes.
> 
> Why'd you change it from:
> https://github.com/tpm2-software/tpm2-pkcs11/pull/239/files#diff-c3df73929e97a82485422329ed256f2cL563
> 
> ```c
>             tmp = ec_fixup_size(opdata->mtype, opdata->tobj, signature_len);
>             if (tmp != CKR_OK) {
> ```

To comply with the "correct coding style/standard" according to you:
https://github.com/tpm2-software/tpm2-pkcs11/pull/226#discussion_r285188439

**Comment by williamcroberts** [comment]
> > > > > Same problem as always.
> > > > > if (rv) vs if(!ptr) ....
> > > > > if (rv) vs if(!ptr) ....
> > > > 
> > > > 
> > > > I've done that myself, many times.
> > > 
> > > 
> > > That's why I prefer the explicit version for regular return codes.
> > 
> > 
> > Why'd you change it from:
> > https://github.com/tpm2-software/tpm2-pkcs11/pull/239/files#diff-c3df73929e97a82485422329ed256f2cL563
> > ```c
> >             tmp = ec_fixup_size(opdata->mtype, opdata->tobj, signature_len);
> >             if (tmp != CKR_OK) {
> > ```
> 
> To comply with the "correct coding style/standard" according to you:
> [#226 (comment)](https://github.com/tpm2-software/tpm2-pkcs11/pull/226#discussion_r285188439)

I meant to not bury the function call in a conditional statement. It has nothing to do with the the conditional check. if(x) and if (x != OK) are both OK however if (foo()) or if (foo != OK) are NOT OK.

**Comment by PeterHuewe** [comment]
> > I'll look into why the tests fail....
> 
> Probably add a regression test too. We need to get in the habit of adding a test when we fix a bug.
Done - I modified the existing test cases that they test that the reported size is larger or equal the actual size.

**Pull request merged**
