### PR TITLE
Add SHA1 as hashalg/mgf for CKM_RSA_PKCS_OAEP

### LINKED ISSUE #249: tpm2_ptool addkey: Add support to specify mgf/hashalg for oaep
Currently any key created using tpm2_ptool addkey has for the OEAP mechanism parameters                     `"hashalg": CKM_SHA256 `and `"mgf": CKG_MGF1_SHA256` set.

However there are use cases where I need hashalg and mgf to be set to SHA_1.

-> Add support to select this as an option.

### PR DESCRIPTION
**Pull request by PeterHuewe**
There are certain legacy use cases which still want to use SHA1 as mgf/hashalg.
By specifying both mechanisms in the template, the current logic checks both of
them if they match the requested one from the user.

Fixes #249 

Signed-off-by: Peter Huewe <peter.huewe@infineon.com>

### CODE REVIEW

**Comment by PeterHuewe** [comment]
Build fails due to some unknown reason, regardless of the change itself (see master is failing).
tpm2-tools or tpm2-tss update probably broke something.

**Comment by williamcroberts** [comment]
> Build fails due to some unknown reason, regardless of the change itself (see master is failing).
> tpm2-tools or tpm2-tss update probably broke something.

PR: https://github.com/tpm2-software/tpm2-tools/pull/1537

For some reason locally make check seems to be hanging now, or is going really slowly. Ill let it run for awhile....

**Comment by williamcroberts** [comment]
> > Build fails due to some unknown reason, regardless of the change itself (see master is failing).
> > tpm2-tools or tpm2-tss update probably broke something.
> 
> PR: [tpm2-software/tpm2-tools#1537](https://github.com/tpm2-software/tpm2-tools/pull/1537)
> 
> For some reason locally make check seems to be hanging now, or is going really slowly. Ill let it run for awhile....

Just slow...

**Comment by williamcroberts** [comment]
build restarted

**Pull request merged**
