### PR TITLE
Do not use sequence to calculate expected ECDSA signature length

### LINKED ISSUE #741: Mutual TLS in browser (Firefox or Chrome) fails
Hello,

I have spend some time in the last few days trying to get tpm2-pkcs11 to work and I have been somewhat successful using `curl` with OpenSSL engine.
Environment:
  * Qemu virtual Debian 11 amd64
  * vTPM in qemu (swtpm) / TPM2 - TIS
  * packages used:
```
ii  libtpm2-pkcs11-1                      1.5.0-4
ii  libtpm2-pkcs11-tools                  1.5.0-4
ii  python3-tpm2-pkcs11-tools             1.5.0-4
```

However, it seems that using the pkcs11 module in Firefox or Chrome to do mutual TLS is not working properly.
I can load the PKCS11 module and see the certificate, however when challenged to perform a mutual TLS, I get the prompt to select the certificate and then the TLS session stops there.

Error in Firefox: `SEC_ERROR_OUTPUT_LEN`
Error in Chrome: `ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED` 

Truncated PKCS11SPY output when failing:
```
92: C_FindObjectsInit
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
[in] pTemplate[2]: 
    CKA_VALUE             00007f8837c5e318 / 634
    00000000  30 82 02 76 30 82 02 1B A0 03 02 01 02 02 14 76  0..v0..........v
...
    00000270  96 9C D0 6C 8D EE E1 6E 3D BD                    ...l...n=.      
    CKA_CLASS             CKO_CERTIFICATE      
Returned:  0 CKR_OK

...

96: C_GetAttributeValue
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
[in] hObject = 0x3
[in] pTemplate[2]: 
    CKA_ID                00007f8834b76020 / 4
    CKA_CLASS             00007f8834b76028 / 8
[out] pTemplate[2]: 
    CKA_ID                00007f8834b76020 / 4
    00000000  31 32 33 34                                      1234            
    CKA_CLASS             CKO_CERTIFICATE      
Returned:  0 CKR_OK

97: C_FindObjectsInit
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
[in] pTemplate[2]: 
    CKA_ID                00007f8834b76020 / 4
    00000000  31 32 33 34                                      1234            
    CKA_CLASS             CKO_PRIVATE_KEY      
Returned:  0 CKR_OK

98: C_FindObjects
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
[in] ulMaxObjectCount = 0x1
[out] ulObjectCount = 0x1
Object 0x1 matches
Returned:  0 CKR_OK

99: C_FindObjectsFinal
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
Returned:  0 CKR_OK

100: C_GetAttributeValue
2021-11-18 15:47:46.490
[in] hSession = 0x100000000000001
[in] hObject = 0x1
[in] pTemplate[1]: 
    CKA_KEY_TYPE          00007fff7ce9eb58 / 8
[out] pTemplate[1]: 
    CKA_KEY_TYPE          CKK_EC             
Returned:  0 CKR_OK

...

104: C_GetAttributeValue
2021-11-18 15:47:46.492
[in] hSession = 0x100000000000001
[in] hObject = 0x1
[in] pTemplate[1]: 
    CKA_ECDSA_PARAMS      0000000000000000 / 0
[out] pTemplate[1]: 
    CKA_ECDSA_PARAMS      0000000000000000 / 10
Returned:  0 CKR_OK

...

108: C_SignInit
2021-11-18 15:47:46.492
[in] hSession = 0x100000000000002
pMechanism->type=CKM_ECDSA                    
[in] hKey = 0x1
Returned:  0 CKR_OK

...

110: C_Sign
2021-11-18 15:47:46.512
[in] hSession = 0x100000000000002
[in] pData[ulDataLen] 00007f8846cbd788 / 32
    00000000  AA BE 27 DC 4F 0B 36 03 01 DD 2E 09 E2 4E C9 E3  ..'.O.6......N..
    00000010  13 93 8E 82 9C 70 56 48 DB F7 C3 73 A7 85 53 3C  .....pVH...s..S<
Returned:  336 CKR_BUFFER_TOO_SMALL

111: C_CloseSession
2021-11-18 15:47:46.512
[in] hSession = 0x100000000000002
Returned:  0 CKR_OK
```
We can see that somehow `tpm2-pkcs11` library returns a CKR_BUFFER_TOO_SMALL error.

I am able to use `curl` on the command line with the library and identical objects so something is off for the browsers to fail.
My gut feeling is that the implementation of C_Sign in tpm2-pkcs11 is not honoring the calling convention to provide back the buffer size required when the data pointer is NULL so that the application can allocate the required buffer.
It's likely curl/openssl engine preallocate the right buffer and don't trigger the same issue.
I believe some logic for that calling convention exists in the C_Digest (there's even a unit-test for it but the same is not true for C_Sign as far as I can tell).

Does that make sense?

### PR DESCRIPTION
**Pull request by calderonth**
This should fix #741.

### CODE REVIEW

**Review by williamcroberts — APPROVED** [review]

**Comment by calderonth** [comment]
No too sure why those tests failed?

**Comment by calderonth** [comment]
Hey there @williamcroberts anythine else needed to merge this in?

**Comment by williamcroberts** [comment]
> Hey there @williamcroberts anythine else needed to merge this in?

CI needs to pass, it's flunking: test_sign_verify_CKM_ECDSA

**Comment by calderonth** [comment]
Ah right the test was still expecting a size with the DER encoded length, I've adjusted to the expected size for P256 in the test.

**Comment by calderonth** [comment]
Will the CI kick-in again to perform all the tests?

**Comment by williamcroberts** [comment]
> Will the CI kick-in again to perform all the tests?

I guess now with GitHub a maintainer has to approve every run. It's kicked off now

**Comment by calderonth** [comment]
Seems all good now?

**Comment by williamcroberts** [comment]
> Seems all good now?

Sorry for the delay, merged.

**Pull request merged**
