### PR TITLE
object: implement C_DestroyObject()

### LINKED ISSUE #144: Add support for C_DestroyObject
Since we (soon) can create keys, it would be great to also get rid of them again.

### PR DESCRIPTION
**Pull request by williamcroberts**
Implement C_DestroyObject by reference counting when tobjects are in use
internally in the library across operations. If C_Destroy() occurs when
the reference count is > 1, then it should fail with
CKR_FUNCTION_FAILED. Otherwise, delete it from the token tobject list
and and remove the DB entry.

Fixes #144

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
Intresting, p11tool --delete never calls C_FindObjectsFinal() before issuing the C_DestroyObject:
```
INFO on line: "459" in file: "src/pkcs11.c": enter "C_Login"
INFO on line: "459" in file: "src/pkcs11.c": return "C_Login" value: 0
INFO on line: "491" in file: "src/pkcs11.c": enter "C_FindObjectsInit"
INFO on line: "491" in file: "src/pkcs11.c": return "C_FindObjectsInit" value: 0
INFO on line: "495" in file: "src/pkcs11.c": enter "C_FindObjects"
INFO on line: "495" in file: "src/pkcs11.c": return "C_FindObjects" value: 0
INFO on line: "475" in file: "src/pkcs11.c": enter "C_DestroyObject"
```

**Comment by PeterHuewe** [comment]
```
../../src/lib/db.c: In function 'db_delete_object':
../../src/lib/db.c:1636:31: error: unused parameter 'tok' [-Werror=unused-parameter]
 CK_RV db_delete_object(token *tok, tobject *tobj) {
```

**Comment by williamcroberts** [comment]
> ```
> ../../src/lib/db.c: In function 'db_delete_object':
> ../../src/lib/db.c:1636:31: error: unused parameter 'tok' [-Werror=unused-parameter]
>  CK_RV db_delete_object(token *tok, tobject *tobj) {
> ```

Yep, fixed in the newest PR. Also went and did a commit that deals with issues using p11tool and pkcs11-tool for keygen/delete and added information on using those tools to the docs.

**Comment by williamcroberts** [comment]
> ```
> ../../src/lib/db.c: In function 'db_delete_object':
> ../../src/lib/db.c:1636:31: error: unused parameter 'tok' [-Werror=unused-parameter]
>  CK_RV db_delete_object(token *tok, tobject *tobj) {
> ```

Yep, fixed in the newest PR. Also went and did a commit that deals with issues using p11tool and pkcs11-tool for keygen/delete and added information on using those tools to the docs.

**Comment by williamcroberts** [comment]
> ```
> ../../src/lib/db.c: In function 'db_delete_object':
> ../../src/lib/db.c:1636:31: error: unused parameter 'tok' [-Werror=unused-parameter]
>  CK_RV db_delete_object(token *tok, tobject *tobj) {
> ```

Yep, fixed in the newest PR. Also went and did a commit that deals with issues using p11tool and pkcs11-tool for keygen/delete and added information on using those tools to the docs.

**Comment by williamcroberts** [comment]
weird travis and dco checks are not firing...

**Pull request merged**
