### PR TITLE
Revert "Tests: Add p11tool tests"

### PR DESCRIPTION
**Pull request by williamcroberts**
For some reason tests are hanging, and it's not the nss tests. Perhaps its the p11tool tests?

### CODE REVIEW

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT sorry I had to revert your changes, on DOCKER_TAG=fedora-30, issues....

**Comment by AndreasFuchsSIT** [comment]
Ok, so on gcc I was able to get the error done. It was a double-entry via p11-kit.

On clang, it hangs. This is the gdb-trace:
```c
$ gdb -p $(pidof p11tool | cut -d " " -f 1)
[... a bunch of symbol resolutions ...]
(gdb) bt
#0  futex_abstimed_wait (private=0, abstime=0x0, expected=2, futex_word=<optimized out>) at ../sysdeps/unix/sysv/linux/futex-internal.h:172
#1  __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x7f0f026779a0 <__libc_setlocale_lock>) at pthread_rwlock_common.c:807
#2  __GI___pthread_rwlock_wrlock (rwlock=0x7f0f026779a0 <__libc_setlocale_lock>) at pthread_rwlock_wrlock.c:27
#3  0x00007f0f024e5ab7 in __newlocale (category_mask=<optimized out>, category_mask@entry=8127, locale=locale@entry=0x7f0eff1bfd61 "POSIX", base=<optimized out>, base@entry=0x0) at newlocale.c:163
#4  0x00007f0eff1b66a1 in p11_library_init_impl () at ../common/library.c:160
#5  0x00007f0f03344f4a in call_init (l=<optimized out>, argc=argc@entry=4, argv=argv@entry=0x7ffc034f5cb8, env=env@entry=0x7ffc034f5ce0) at dl-init.c:72
#6  0x00007f0f03345051 in call_init (env=0x7ffc034f5ce0, argv=0x7ffc034f5cb8, argc=4, l=<optimized out>) at dl-init.c:30
#7  _dl_init (main_map=main_map@entry=0x61a000000080, argc=4, argv=0x7ffc034f5cb8, env=0x7ffc034f5ce0) at dl-init.c:119
#8  0x00007f0f03348fae in dl_open_worker (a=a@entry=0x7ffc034f4dc0) at dl-open.c:510
#9  0x00007f0f025ece09 in __GI__dl_catch_exception (exception=exception@entry=0x7ffc034f4da0, operate=operate@entry=0x7f0f03348bc0 <dl_open_worker>, args=args@entry=0x7ffc034f4dc0) at dl-error-skeleton.c:196
#10 0x00007f0f0334882e in _dl_open (file=0x604000000510 "/usr/lib64/pkcs11/p11-kit-trust.so", mode=-2147483646, caller_dlopen=0x7f0f02910c74 <__interceptor_dlopen(char const*, int)+244>, nsid=-2, argc=4, 
    argv=<optimized out>, env=0x7ffc034f5ce0) at dl-open.c:592
#11 0x00007f0f0229b39c in dlopen_doit (a=a@entry=0x7ffc034f4fe0) at dlopen.c:66
#12 0x00007f0f025ece09 in __GI__dl_catch_exception (exception=exception@entry=0x7ffc034f4f80, operate=operate@entry=0x7f0f0229b340 <dlopen_doit>, args=args@entry=0x7ffc034f4fe0) at dl-error-skeleton.c:196
#13 0x00007f0f025ecea3 in __GI__dl_catch_error (objname=objname@entry=0x7f0f032aedb0 <alloc_memory_for_dlsym+16>, errstring=errstring@entry=0x7f0f032aedb8 <alloc_memory_for_dlsym+24>, 
    mallocedp=mallocedp@entry=0x7f0f032aeda8 <alloc_memory_for_dlsym+8>, operate=operate@entry=0x7f0f0229b340 <dlopen_doit>, args=args@entry=0x7ffc034f4fe0) at dl-error-skeleton.c:215
#14 0x00007f0f0229bb09 in _dlerror_run (operate=operate@entry=0x7f0f0229b340 <dlopen_doit>, args=args@entry=0x7ffc034f4fe0) at dlerror.c:170
#15 0x00007f0f0229b42a in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#16 0x00007f0f02910c74 in __interceptor_dlopen (filename=0x604000000510 "/usr/lib64/pkcs11/p11-kit-trust.so", flag=2)
    at /usr/src/debug/compiler-rt-8.0.0-1.fc30.x86_64/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:5969
#17 0x00007f0f0202b4fc in dlopen_and_get_function_list (funcs=0x7ffc034f58a0, path=0x604000000510 "/usr/lib64/pkcs11/p11-kit-trust.so", mod=0x617000000080) at ../p11-kit/modules.c:429
#18 load_module_from_file_inlock (path=0x604000000510 "/usr/lib64/pkcs11/p11-kit-trust.so", result=result@entry=0x7ffc034f5928, name=<optimized out>) at ../p11-kit/modules.c:429
#19 0x00007f0f0202baa7 in take_config_and_load_module_inlock (verbose=false, critical=false, config=0x7ffc034f5920, name=0x7ffc034f5918) at ../p11-kit/modules.c:597
#20 load_registered_modules_unlocked (flags=flags@entry=0) at ../p11-kit/modules.c:682
#21 0x00007f0f0202c89f in load_registered_modules_unlocked (flags=0) at ../p11-kit/modules.c:2032
#22 p11_modules_load_inlock_reentrant (flags=0, results=0x7ffc034f5a20) at ../p11-kit/modules.c:1987
#23 0x00007f0f0202c927 in p11_kit_modules_load (reserved=0x0, flags=0) at ../p11-kit/modules.c:2092
#24 0x00007f0f0202ccb2 in p11_kit_modules_load_and_initialize (flags=flags@entry=0) at ../p11-kit/modules.c:2216
#25 0x00007f0f0274c3ca in auto_load (trusted=trusted@entry=0) at pkcs11.c:933
#26 0x00007f0f0274de37 in gnutls_pkcs11_init (flags=1, deprecated_config_file=0x0) at pkcs11.c:1006
#27 0x0000557d8b3c3bf3 in cmd_parser (argv=<optimized out>, argc=8) at p11tool.c:187
#28 main (argc=<optimized out>, argv=<optimized out>) at p11tool.c:75
```

@williamcroberts Any idea, have you seen anything similar ever ?

**Comment by williamcroberts** [comment]
> -----Original Message-----
> From: Andreas Fuchs [mailto:notifications@github.com]
> Sent: Wednesday, April 1, 2020 6:09 AM
> To: tpm2-software/tpm2-pkcs11 <tpm2-pkcs11@noreply.github.com>
> Cc: Roberts, William C <william.c.roberts@intel.com>; Mention
> <mention@noreply.github.com>
> Subject: Re: [tpm2-software/tpm2-pkcs11] Revert "Tests: Add p11tool tests"
> (#467)
> 
> Ok, so on gcc I was able to get the error done. It was a double-entry via p11-kit.
> 
> On clang, it hangs. This is the gdb-trace:
> 
> $ gdb -p $(pidof p11tool | cut -d " " -f 1) [... a bunch of symbol resolutions ...]
> (gdb) bt
> #0  futex_abstimed_wait (private=0, abstime=0x0, expected=2,
> futex_word=<optimized out>) at ../sysdeps/unix/sysv/linux/futex-internal.h:172
> #1  __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x7f0f026779a0
> <__libc_setlocale_lock>) at pthread_rwlock_common.c:807
> #2  __GI___pthread_rwlock_wrlock (rwlock=0x7f0f026779a0
> <__libc_setlocale_lock>) at pthread_rwlock_wrlock.c:27
> #3  0x00007f0f024e5ab7 in __newlocale (category_mask=<optimized out>,
> category_mask@entry=8127, locale=locale@entry=0x7f0eff1bfd61 "POSIX",
> base=<optimized out>, base@entry=0x0) at newlocale.c:163
> #4  0x00007f0eff1b66a1 in p11_library_init_impl () at ../common/library.c:160
> #5  0x00007f0f03344f4a in call_init (l=<optimized out>, argc=argc@entry=4,
> argv=argv@entry=0x7ffc034f5cb8, env=env@entry=0x7ffc034f5ce0) at dl-
> init.c:72
> #6  0x00007f0f03345051 in call_init (env=0x7ffc034f5ce0, argv=0x7ffc034f5cb8,
> argc=4, l=<optimized out>) at dl-init.c:30
> #7  _dl_init (main_map=main_map@entry=0x61a000000080, argc=4,
> argv=0x7ffc034f5cb8, env=0x7ffc034f5ce0) at dl-init.c:119
> #8  0x00007f0f03348fae in dl_open_worker (a=a@entry=0x7ffc034f4dc0) at dl-
> open.c:510
> #9  0x00007f0f025ece09 in __GI__dl_catch_exception
> (exception=exception@entry=0x7ffc034f4da0,
> operate=operate@entry=0x7f0f03348bc0 <dl_open_worker>,
> args=args@entry=0x7ffc034f4dc0) at dl-error-skeleton.c:196
> #10 0x00007f0f0334882e in _dl_open (file=0x604000000510
> "/usr/lib64/pkcs11/p11-kit-trust.so", mode=-2147483646,
> caller_dlopen=0x7f0f02910c74 <__interceptor_dlopen(char const*, int)+244>,
> nsid=-2, argc=4,
>     argv=<optimized out>, env=0x7ffc034f5ce0) at dl-open.c:592
> #11 0x00007f0f0229b39c in dlopen_doit (a=a@entry=0x7ffc034f4fe0) at
> dlopen.c:66
> #12 0x00007f0f025ece09 in __GI__dl_catch_exception
> (exception=exception@entry=0x7ffc034f4f80,
> operate=operate@entry=0x7f0f0229b340 <dlopen_doit>,
> args=args@entry=0x7ffc034f4fe0) at dl-error-skeleton.c:196
> #13 0x00007f0f025ecea3 in __GI__dl_catch_error
> (objname=objname@entry=0x7f0f032aedb0 <alloc_memory_for_dlsym+16>,
> errstring=errstring@entry=0x7f0f032aedb8 <alloc_memory_for_dlsym+24>,
>     mallocedp=mallocedp@entry=0x7f0f032aeda8 <alloc_memory_for_dlsym+8>,
> operate=operate@entry=0x7f0f0229b340 <dlopen_doit>,
> args=args@entry=0x7ffc034f4fe0) at dl-error-skeleton.c:215
> #14 0x00007f0f0229bb09 in _dlerror_run
> (operate=operate@entry=0x7f0f0229b340 <dlopen_doit>,
> args=args@entry=0x7ffc034f4fe0) at dlerror.c:170
> #15 0x00007f0f0229b42a in __dlopen (file=<optimized out>, mode=<optimized
> out>) at dlopen.c:87
> #16 0x00007f0f02910c74 in __interceptor_dlopen (filename=0x604000000510
> "/usr/lib64/pkcs11/p11-kit-trust.so", flag=2)
>     at /usr/src/debug/compiler-rt-8.0.0-
> 1.fc30.x86_64/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc
> :5969
> #17 0x00007f0f0202b4fc in dlopen_and_get_function_list (funcs=0x7ffc034f58a0,
> path=0x604000000510 "/usr/lib64/pkcs11/p11-kit-trust.so",
> mod=0x617000000080) at ../p11-kit/modules.c:429
> #18 load_module_from_file_inlock (path=0x604000000510
> "/usr/lib64/pkcs11/p11-kit-trust.so", result=result@entry=0x7ffc034f5928,
> name=<optimized out>) at ../p11-kit/modules.c:429
> #19 0x00007f0f0202baa7 in take_config_and_load_module_inlock
> (verbose=false, critical=false, config=0x7ffc034f5920, name=0x7ffc034f5918) at
> ../p11-kit/modules.c:597
> #20 load_registered_modules_unlocked (flags=flags@entry=0) at ../p11-
> kit/modules.c:682
> #21 0x00007f0f0202c89f in load_registered_modules_unlocked (flags=0) at
> ../p11-kit/modules.c:2032
> #22 p11_modules_load_inlock_reentrant (flags=0, results=0x7ffc034f5a20) at
> ../p11-kit/modules.c:1987
> #23 0x00007f0f0202c927 in p11_kit_modules_load (reserved=0x0, flags=0) at
> ../p11-kit/modules.c:2092
> #24 0x00007f0f0202ccb2 in p11_kit_modules_load_and_initialize
> (flags=flags@entry=0) at ../p11-kit/modules.c:2216
> #25 0x00007f0f0274c3ca in auto_load (trusted=trusted@entry=0) at pkcs11.c:933
> #26 0x00007f0f0274de37 in gnutls_pkcs11_init (flags=1,
> deprecated_config_file=0x0) at pkcs11.c:1006
> #27 0x0000557d8b3c3bf3 in cmd_parser (argv=<optimized out>, argc=8) at
> p11tool.c:187
> #28 main (argc=<optimized out>, argv=<optimized out>) at p11tool.c:75
> 
> @williamcroberts <https://github.com/williamcroberts>  Any idea, have you seen
> anything similar ever ?
> 

Never, unfortunately.

**Comment by AndreasFuchsSIT** [comment]
I opened up an upstream issue for this:
https://gitlab.com/gnutls/gnutls/-/issues/965

**Pull request merged**
