### PR TITLE
Added test to reproduce #335

### PR DESCRIPTION
**Pull request by ijaureguiberry**
Added some documentation and scripts to reproduce issue #335 
This is not an automated test, just an aid to solve the issue.
Signed-off-by: Ignacio Jaureguiberry <ignaciox.jaureguiberry@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
Awesome, I can probably turn this into an automated test too

**Comment by williamcroberts** [comment]
@ijaureguiberry Looks like I fixed it on my local branch:
https://github.com/williamcroberts/tpm2-pkcs11/tree/wpa-supplicant

```bash
tpm2ssl s_client -engine pkcs11 -keyform engine -key "pkcs11:model=SW%20%20%20TPM;manufacturer=IBM;serial=0000000000000000;token=label" -CAfile ca.pem -cert client_tpm.pem 127.0.0.1 <<< 'Q'
# <snip>
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3058 bytes and written 2964 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
DONE

echo $?
0
```

I'm going to clean this up, add some tests and then roll this into RC1 since it was pretty trivial and has some nice bug fixes along the way. However, this show cases that #365 really needs to be done. The mechanism handling code is awful.

Reminder for myself: in s_client echo Q to stdin to get it to quit. Useful for testing script forthcoming.

**Comment by williamcroberts** [comment]
@ijaureguiberry this test is added into the integration tests and is now passing locally, awaiting CI results.

See:
  - https://github.com/tpm2-software/tpm2-pkcs11/pull/366

**Comment by ijaureguiberry** [comment]
@williamcroberts I can't reproduce your results. I've reached almost the same as your output, except for the last line:

```
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3058 bytes and written 2964 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
140533871120832:error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error:../ssl/record/rec_layer_s3.c:1528:SSL alert number 51
```

On the server side I can see this:

```
depth=1 C = FR, ST = Radius, L = Somewhere, O = Example Inc., emailAddress = admin@example.org, CN = Example Certificate Authority
verify return:1
depth=0 C = FR, ST = Radius, O = Example Inc., CN = testing, emailAddress = testing@123.com
verify return:1
ERROR
140369078280640:error:0407E086:rsa routines:RSA_verify_PKCS1_PSS_mgf1:last octet invalid:../crypto/rsa/rsa_pss.c:88:
140369078280640:error:1417B07B:SSL routines:tls_process_cert_verify:bad signature:../ssl/statem/statem_lib.c:492:
shutting down SSL
CONNECTION CLOSED
```

I've noted you call tpm2ssl instead of openssl, do you have a patched openssl or fork?

I've also tested with wpa\_supplicant, and it still tries using CKM_RSA_X_509, this comes from openssl and libp11: https://github.com/OpenSC/libp11/blob/a41cbb29083545ceee8da35fa0067e402ed7d676/src/p11_rsa.c#L62 and https://github.com/openssl/openssl/blob/dbcf53f867146766845f6e64243208d87007f970/crypto/rsa/rsa_pmeth.c#L176

The FreeRADIUS server logs shows this:
```
(6) eap: Calling submodule eap_tls to process data
(6) eap_tls: Continuing EAP-TLS
(6) eap_tls: Got final TLS record fragment (1263 bytes)
(6) eap_tls: [eaptls verify] = ok
(6) eap_tls: Done initial handshake
(6) eap_tls: TLS_accept: SSLv3/TLS write server done
(6) eap_tls: <<< recv TLS 1.2  [length 08d5] 
(6) eap_tls: TLS - Creating attributes from certificate OIDs
(6) eap_tls:   TLS-Cert-Serial := "6e9b8d5b0cb4e90a58f76fcf9b511df9fceff97e"
(6) eap_tls:   TLS-Cert-Expiration := "191229140718Z"
(6) eap_tls:   TLS-Cert-Subject := "/C=FR/ST=Radius/L=Somewhere/O=Example Inc./emailAddress=admin@example.org/CN=Example Certificate Authority"
(6) eap_tls:   TLS-Cert-Issuer := "/C=FR/ST=Radius/L=Somewhere/O=Example Inc./emailAddress=admin@example.org/CN=Example Certificate Authority"
(6) eap_tls:   TLS-Cert-Common-Name := "Example Certificate Authority"
(6) eap_tls: TLS - Creating attributes from certificate OIDs
(6) eap_tls:   TLS-Client-Cert-Serial := "08"
(6) eap_tls:   TLS-Client-Cert-Expiration := "200216143337Z"
(6) eap_tls:   TLS-Client-Cert-Subject := "/C=FR/ST=Radius/O=Example Inc./CN=testing7/emailAddress=testing@123.com"
(6) eap_tls:   TLS-Client-Cert-Issuer := "/C=FR/ST=Radius/L=Somewhere/O=Example Inc./emailAddress=admin@example.org/CN=Example Certificate Authority"
(6) eap_tls:   TLS-Client-Cert-Common-Name := "testing7"
(6) eap_tls:   TLS-Client-Cert-X509v3-Extended-Key-Usage += "TLS Web Client Authentication"
(6) eap_tls:   TLS-Client-Cert-X509v3-Extended-Key-Usage-OID += "1.3.6.1.5.5.7.3.2"
(6) eap_tls: TLS_accept: SSLv3/TLS read client certificate
(6) eap_tls: <<< recv TLS 1.2  [length 0046] 
(6) eap_tls: TLS_accept: SSLv3/TLS read client key exchange
(6) eap_tls: <<< recv TLS 1.2  [length 0108] 
(6) eap_tls: >>> send TLS 1.2  [length 0002] 
(6) eap_tls: ERROR: TLS Alert write:fatal:decrypt error
tls: TLS_accept: Error in error
(6) eap_tls: ERROR: Failed in __FUNCTION__ (SSL_read)
(6) eap_tls: ERROR: error:0407E085:rsa routines:RSA_verify_PKCS1_PSS_mgf1:first octet invalid
(6) eap_tls: ERROR: error:1417B07B:SSL routines:tls_process_cert_verify:bad signature
(6) eap_tls: ERROR: System call (I/O) error (-1)
(6) eap_tls: ERROR: TLS receive handshake failed during operation
(6) eap_tls: ERROR: [eaptls process] = fail
(6) eap: ERROR: Failed continuing EAP TLS (13) session.  EAP sub-module failed
(6) eap: Sending EAP Failure (code 4) ID 6 length 4
(6) eap: Failed in EAP select
(6)     [eap] = invalid
(6)   } # authenticate = invalid
(6) Failed to authenticate the user
```

If the `CKM_RSA_X_509` mechanism is not going to be supported, I think I need to find a way for openssl to use other method, not sure that's possible.

**Pull request closed without merging**
