### PR TITLE
FAPI: Add delete and set attribute

### LINKED ISSUE #471: FAPI: Add C_SetAttributeValue support
PR #470 will bring in C_SetAttributeValue support, and thus modifies and persists the values to the backend. This will be implemented for ESYS backend, but FAPI will need to implement it to.

### LINKED ISSUE #472: FAPI: Support C_DestroyObject
PR #470 will bring in C_SetAttributeValue support, and thus modifies and persists the values to the backend. This will be implemented for ESYS backend, but FAPI will need to implement it to.

### PR DESCRIPTION
**Pull request by AndreasFuchsSIT**
My problem: I don't know how to test UpdateAttributes for FAPI backend right now.
Can this be triggered by pkcs11-tool or p11-tool ?

(includes #482)

Fixes #471 
Fixes #472

### CODE REVIEW

**Comment by williamcroberts** [comment]
> My problem: I don't know how to test UpdateAttributes for FAPI backend right now.
> Can this be triggered by pkcs11-tool or p11-tool ?

So the SetAtrribute call that I saw came in for Sun Java PKCS11 provider, see:
  - https://github.com/tpm2-software/tpm2-pkcs11/issues/468

Looks like pkcs11-tool allows a little support:
```
      --private                 Set the CKA_PRIVATE attribute (object is only viewable after a login)
      --sensitive               Set the CKA_SENSITIVE attribute (object cannot be revealed in plaintext)
```
p11tool has some in the form of `--mark-xxx` and `--no-mark-xxx` options.


> 
> (includes #482)
> 
> Fixes #471
> Fixes #472

**Comment by williamcroberts** [comment]
@AndreasFuchsSIT LGTM, mark this non-draft when you want a final review and merge.

**Comment by AndreasFuchsSIT** [comment]
@williamcroberts undrafted... :-)

**Comment by williamcroberts** [comment]
> @williamcroberts undrafted... :-)

un-not-merged

**Comment by AndreasFuchsSIT** [comment]
> > My problem: I don't know how to test UpdateAttributes for FAPI backend right now.
> > Can this be triggered by pkcs11-tool or p11-tool ?
> 
> So the SetAtrribute call that I saw came in for Sun Java PKCS11 provider, see:
> 
>     * #468
> 
> 
> Looks like pkcs11-tool allows a little support:
> 
> ```
>       --private                 Set the CKA_PRIVATE attribute (object is only viewable after a login)
>       --sensitive               Set the CKA_SENSITIVE attribute (object cannot be revealed in plaintext)
> ```
> 
> p11tool has some in the form of `--mark-xxx` and `--no-mark-xxx` options.

Yes, I tried these, but they are only used upon key / object creation. So I assumed they send the attribute value in the parameter set. But not call SetAttribute...

I'll look into the Java stuff though...

**Pull request merged**
