### PR TITLE
Fix 553

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Comment by williamcroberts** [comment]
Interesting, my investigation into this break shows that the break occurs because the C_SignInit now passes, causing the TPM to perform the PSS operation. Before it would fail causing it to fall back to using CKM_RSA_X_509. I wonder what the pss signature status is?

**Comment by williamcroberts** [comment]
> Interesting, my investigation into this break shows that the break occurs because the C_SignInit now passes, causing the TPM to perform the PSS operation. Before it would fail causing it to fall back to using CKM_RSA_X_509. I wonder what the pss signature status is?

It's claiming good. What happens if I set verify to -2, to maximize salt length?

**Comment by williamcroberts** [comment]
> > Interesting, my investigation into this break shows that the break occurs because the C_SignInit now passes, causing the TPM to perform the PSS operation. Before it would fail causing it to fall back to using CKM_RSA_X_509. I wonder what the pss signature status is?
> 
> It's claiming good. What happens if I set verify to -2, to maximize salt length?

Still fails... hrmmmm
```
INFO on line: "179" in file: "../src/lib/sign.c": token(1): pss signature state: good
INFO on line: "547" in file: "../src/pkcs11.c": return "C_SignInit" value: 0
INFO on line: "551" in file: "../src/pkcs11.c": enter "C_Sign"
INFO on line: "551" in file: "../src/pkcs11.c": return "C_Sign" value: 0
+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-2 -signature data.sig -verify pubkey.pem data.txt
Verification Failure
++ onerror
++ echo 'openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-2 -signature data.sig -verify pubkey.pem data.txt on line 118 failed: 1'
openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-2 -signature data.sig -verify pubkey.pem data.txt on line 118 failed: 1
++ exit 1
```

Whats also of importance is OSSL version:
1.1.1 (Ubuntu-18.04) and 1.0.2g (Ubuntu-16.04) work. but 1.1.1f (ubuntu 20.04) seems to be having the issue.

**Comment by williamcroberts** [comment]
Interesting, I hacked up the openssl.sh script to test all possible pss saltlen options with nothing passing verification:

+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:digest -signature data.sig -verify pubkey.pem data.txt
Verification Failure
+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:max -signature data.sig -verify pubkey.pem data.txt
Verification Failure
+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:auto -signature data.sig -verify pubkey.pem data.txt
Verification Failure
+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature data.sig -verify pubkey.pem data.txt
Verification Failure
+ openssl dgst -sha256 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-2 -signature data.sig -verify pubkey.pem data.txt
Verification Failure
+ exit 1

**Comment by williamcroberts** [comment]
I guess let me try and copy the PEM public key and signature and verify it with openssl 1.1.1 on my other system.

**Comment by williamcroberts** [comment]
> I guess let me try and copy the PEM public key and signature and verify it with openssl 1.1.1 on my other system.

Same fails, so it seems it's not an OpenSSL version issue, despite the fact that it works on:
- Ubuntu 16.04 https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/718774662#L3988
- Ubuntu 18.04 https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/718774663#L3862

Perhaps this is a TPM version issue between container images or perhaps that code path is just broken?

**Comment by williamcroberts** [comment]
> > I guess let me try and copy the PEM public key and signature and verify it with openssl 1.1.1 on my other system.
> 
> Same fails, so it seems it's not an OpenSSL version issue, despite the fact that it works on:
> 
> * Ubuntu 16.04 https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/718774662#L3988
> * Ubuntu 18.04 https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/718774663#L3862
> 
> Perhaps this is a TPM version issue between container images or perhaps that code path is just broken?

```
ERROR on line: "1180" in file: "../src/lib/tpm.c": BILL: op_type(0x0): 0x0
ERROR on line: "1182" in file: "../src/lib/tpm.c": BILL: scheme(0x16): 0x16
ERROR on line: "1183" in file: "../src/lib/tpm.c": BILL: halg(0xb): 0xb
ERROR on line: "1185" in file: "../src/lib/tpm.c": BILL2: scheme(0x16): 0x16
ERROR on line: "1186" in file: "../src/lib/tpm.c": BILL2: halg(0xb): 0xb
```

I just realized my docker container locally was stale, it was set with IBM TPM 1628, when the newest is 1637. Perhaps 1628 is broken, but in a different way? Not really sure why, considering that the python code for checking PSS signatures shows it as good. Lets try verifying this with python, just to rule out OSSL.

**Comment by williamcroberts** [comment]
I tried the attached python program with the output data, signature and public key failing signature.
[test-broken.zip](https://github.com/tpm2-software/tpm2-pkcs11/files/5090957/test-broken.zip)

**Comment by williamcroberts** [comment]
I have test code at the bottom of openssl.sh that uses pkcs11 tool directly, along with openssl verify, does that work?

**Comment by williamcroberts** [comment]
> I have test code at the bottom of openssl.sh that uses pkcs11 tool directly, along with openssl verify, does that work?

Yes this test works, and comes in with mechanism 0xE(CKM_SHA1_RSA_PKCS_PSS) vs 0xD(CKM_RSA_PKCS_PSS). However, I think I see the issue. We would expect the paramters to Esys_Sign to be the same, however the hash seems wrong. I added an openssl sign using sha1, so we could compare that input to the known good.

### Good
```
ERROR on line: "1150" in file: "../src/lib/tpm.c": BILL tobject id: 6
ERROR on line: "1169" in file: "../src/lib/tpm.c": BILL SIGN DIGEST(20): 0xb7 0xf8 0xaf 0xf2
ERROR on line: "1190" in file: "../src/lib/tpm.c": BILL: op_type(0x0): 0x0
ERROR on line: "1192" in file: "../src/lib/tpm.c": BILL: scheme(0x16): 0x16
ERROR on line: "1193" in file: "../src/lib/tpm.c": BILL: halg(0xb): 0x4
ERROR on line: "1195" in file: "../src/lib/tpm.c": BILL2: scheme(0x16): 0x16
ERROR on line: "1196" in file: "../src/lib/tpm.c": BILL2: halg(0xb): 0x4
ERROR on line: "1042" in file: "../src/lib/tpm.c": BILL siglen: 256
ERROR on line: "1043" in file: "../src/lib/tpm.c": BILL sig[4]: 0x93 0xe2 0x58 0xfc ...
ERROR on line: "1045" in file: "../src/lib/tpm.c": BILL sigmem equal? yes
```
### Bad
```
ERROR on line: "1150" in file: "../src/lib/tpm.c": BILL tobject id: 6
ERROR on line: "1169" in file: "../src/lib/tpm.c": BILL SIGN DIGEST(20): 0xb6 0x28 0xad 0xf
ERROR on line: "1190" in file: "../src/lib/tpm.c": BILL: op_type(0x0): 0x0
ERROR on line: "1192" in file: "../src/lib/tpm.c": BILL: scheme(0x16): 0x16
ERROR on line: "1193" in file: "../src/lib/tpm.c": BILL: halg(0xb): 0x4
ERROR on line: "1195" in file: "../src/lib/tpm.c": BILL2: scheme(0x16): 0x16
ERROR on line: "1196" in file: "../src/lib/tpm.c": BILL2: halg(0xb): 0x4
ERROR on line: "1042" in file: "../src/lib/tpm.c": BILL siglen: 256
ERROR on line: "1043" in file: "../src/lib/tpm.c": BILL sig[4]: 0xb5 0x99 0xc5 0x72 ...
ERROR on line: "1045" in file: "../src/lib/tpm.c": BILL sigmem equal? yes
```
The hash's don't line up... that's odd. It appears that the bad case is getting double hashed:
openssl dgst -sha1 -binary data.txt | openssl dgst -sha1 = b628ad0fa34a92d8b1d95334883334e9af2316dd
openssl dgst -sha1 data.txt = b7f8aff2d81e5a4c1c626e15e989c75b54f20124

So the fix is simple, stop hashing on CKM_RSA_PKCS_PSS

**Comment by williamcroberts** [comment]
facepalm... per the spec:
The PKCS #1 RSA PSS mechanism, denoted CKM_RSA_PKCS_PSS, is a mechanism based on the RSA public-key cryptosystem and the PSS block format defined in PKCS #1.  It supports single-part signature generation and verification without message recovery. This mechanism corresponds only to the part of PKCS #1 that involves block formatting and RSA, **given a hash value; it does not compute a hash value on the message to be signed**.

**Comment by williamcroberts** [comment]
So this leaves why the difference between OpenSSL 1.1.1 and OpenSSL 1.1.1f. It seems as though the behavior changed and one version of openssl would only use raw rsa and synthesize pss, the other would use the pss algorithm directly.

So the initial patch in this series exposed this bug in PSS mechanism handling, but then the bug only appeared on OSSL versions not using raw x509 rsa.

**Comment by williamcroberts** [comment]
@dnoliver didn't you report something about TLS 1.2 to 1.3 not working regarding PSS signatures? I searched high and low through issues and didn't find anything, but IIRC this patch may fix your issues.

**Comment by magmastonealex** [comment]
I've been pulling my hair out trying to figure out why this wasn't working before I found this PR. Just wanted to say thanks for fixing this, and it's resolved my issues :smile: 

My app is written in `go`, and the existing PKCS11 helpers didn't have any fallback to raw RSA if `CKM_RSA_PKCS_PSS` failed (and I wasn't looking forward to having to write that). With this patch, everything seems to work perfectly for TLS 1.3.

**Comment by dnoliver** [comment]
@williamcroberts I reported the TLS 1.2 to 1.3 with PSS signatures problem for the EAP-TLS authentication problem with RADIUS.

The tpm2 list discussion about that is here https://lists.01.org/hyperkitty/list/tpm2@lists.01.org/thread/QJ6DJSGADFVDJYEFQMYTZYBW4LQBF54N/

And there were a couple of PRs related to PSS support.

I tested this branch, and I am still getting the same error

```shell
Wed Aug 19 08:55:44 2020 us=203842 Incoming Ciphertext -> TLS
Wed Aug 19 08:55:44 2020 us=203862 SSL state (connect): SSLv3/TLS read server certificate
Wed Aug 19 08:55:44 2020 us=203987 SSL state (connect): TLSv1.3 read server certificate verify
Wed Aug 19 08:55:44 2020 us=204101 SSL state (connect): SSLv3/TLS read finished
Wed Aug 19 08:55:44 2020 us=204162 SSL state (connect): SSLv3/TLS write change cipher spec
Wed Aug 19 08:55:44 2020 us=204332 SSL state (connect): SSLv3/TLS write client certificate
Wed Aug 19 08:55:44 2020 us=204410 PKCS#11: __pkcs11h_openssl_rsa_enc entered - flen=256, from=0x55f2678727a0, to=0x55f267873ae0, rsa=0x55f267856740, padding=3
Wed Aug 19 08:55:44 2020 us=204466 PKCS#11: __pkcs11h_openssl_rsa_enc - return rv=112-'CKR_MECHANISM_INVALID'
Wed Aug 19 08:55:44 2020 us=204521 SSL alert (write): fatal: internal error
Wed Aug 19 08:55:44 2020 us=204596 OpenSSL: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib
Wed Aug 19 08:55:44 2020 us=204643 TLS_ERROR: BIO read tls_read_plaintext error
Wed Aug 19 08:55:44 2020 us=204659 TLS Error: TLS object -> incoming plaintext read error
Wed Aug 19 08:55:44 2020 us=204668 TLS Error: TLS handshake failed
Wed Aug 19 08:55:44 2020 us=204676 PID packet_id_free
```

```shell
[root@openvpn openvpn]# cd tpm2-pkcs11/
[root@openvpn tpm2-pkcs11]# git status 
On branch fix-553
Your branch is up to date with 'williamcroberts/fix-553'.
```

**Comment by williamcroberts** [comment]
@dnoliver I see it complaining about mechanism not supported:
```
Wed Aug 19 08:55:44 2020 us=204410 PKCS#11: __pkcs11h_openssl_rsa_enc entered - flen=256, from=0x55f2678727a0, to=0x55f267873ae0, rsa=0x55f267856740, padding=3
Wed Aug 19 08:55:44 2020 us=204466 PKCS#11: __pkcs11h_openssl_rsa_enc - return rv=112-'CKR_MECHANISM_INVALID'
```
it looks like rsa with RSA_NO_PADDING. Is their any way you could capture the call to PKCS11 that is returning that? Perhaps pkcs11 spy or crank up the log level via `export TPM2_PKCS11_LOG_LEVEL=2`

**Comment by williamcroberts** [comment]
@dnoliver is it this issue: https://github.com/tpm2-software/tpm2-pkcs11/issues/67

**Comment by dnoliver** [comment]
yes! oh I thought this PR was a fix for #67, but it was a fix for something else :D 

Sorry I got confused by notifications.

Anyways, this is the verbose PKCS11 log

```shell
[root@openvpn openvpn-client]# openvpn --config ./client.conf --nobind                                                                                                                                [31/1589]
Wed Aug 19 10:12:26 2020 OpenVPN 2.4.9 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 19 2020                                                           
Wed Aug 19 10:12:26 2020 library versions: OpenSSL 1.1.1g FIPS  21 Apr 2020, LZO 2.10                                                                                                                          
Wed Aug 19 10:12:26 2020 PKCS#11: Adding PKCS#11 provider '/usr/lib64/pkcs11/libtpm2_pkcs11.so.0.0.0'                                                                                                          
INFO on line: "387" in file: "src/pkcs11.c": enter "C_GetFunctionList"                                                                                                                                         
INFO on line: "387" in file: "src/pkcs11.c": return "C_GetFunctionList" value: 0                                                                                                                               
INFO on line: "375" in file: "src/pkcs11.c": enter "C_Initialize"                                                                                                                                              
INFO on line: "41" in file: "src/lib/backend.c": Initializing backends                                                                                                                                         
INFO on line: "67" in file: "src/lib/backend_fapi.c": Calling Fapi_Initialize                                                                                                                                  
INFO on line: "1402" in file: "src/lib/db.c": using TPM2_PKCS11_STORE="/etc/tpm2_pkcs11/tpm2_pkcs11.sqlite3"                                                                                                   
INFO on line: "2167" in file: "src/lib/db.c": Using sqlite3 DB: "/etc/tpm2_pkcs11/tpm2_pkcs11.sqlite3"                                                                                                         
INFO on line: "2125" in file: "src/lib/db.c": No DB upgrade needed                                                                                                                                             
INFO on line: "424" in file: "src/lib/tpm.c": tcti=device:/dev/tpmrm0                                                                                                                                          
INFO on line: "389" in file: "src/lib/mech.c": Updating mech detail table that PSS signatures are: good                                                                                                        
INFO on line: "180" in file: "src/lib/backend.c": Esysdb returned 1 token                                                                                                                                      
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:221:Fapi_List_Finish() FAPI not provisioned.                                                                                                                          
ERROR:fapi:src/tss2-fapi/api/Fapi_List.c:81:Fapi_List() ErrorCode (0x00060034) Entities_List                                                                                                                   
ERROR on line: "233" in file: "src/lib/backend_fapi.c": Listing FAPI token objects failed.                                                                                                                     
WARNING on line: "192" in file: "src/lib/backend.c": Getting tokens from fapi backend failed.                                                                                                                  
INFO on line: "195" in file: "src/lib/backend.c": FAPI + Esysdb returned 1 token                                                                                                                               
INFO on line: "424" in file: "src/lib/tpm.c": tcti=device:/dev/tpmrm0                                                                                                                                          
INFO on line: "224" in file: "src/lib/backend.c": Esysdb + FAPI returned 2 token                                                                                                                               
INFO on line: "375" in file: "src/pkcs11.c": return "C_Initialize" value: 0                                                                                                                                    
INFO on line: "383" in file: "src/pkcs11.c": enter "C_GetInfo"                                                                                                                                                 
WARNING on line: "63" in file: "src/lib/general.c": Could not strtoul(4.0-RC0-6-g580a9f0): Success                                                                                                             
INFO on line: "383" in file: "src/pkcs11.c": return "C_GetInfo" value: 0                                                                                                                                       
INFO on line: "391" in file: "src/pkcs11.c": enter "C_GetSlotList"                                                                                                                                             
INFO on line: "391" in file: "src/pkcs11.c": return "C_GetSlotList" value: 0                                                                                                                                   
INFO on line: "391" in file: "src/pkcs11.c": enter "C_GetSlotList"                                                                                                                                             
INFO on line: "391" in file: "src/pkcs11.c": return "C_GetSlotList" value: 0                                                                                                                                   
INFO on line: "399" in file: "src/pkcs11.c": enter "C_GetTokenInfo"                                                                                                                                            
INFO on line: "399" in file: "src/pkcs11.c": return "C_GetTokenInfo" value: 0                                                                                                                                  
INFO on line: "427" in file: "src/pkcs11.c": enter "C_OpenSession"                                                                                                                                             
INFO on line: "427" in file: "src/pkcs11.c": return "C_OpenSession" value: 0                                                                                                                                   
INFO on line: "483" in file: "src/pkcs11.c": enter "C_FindObjectsInit"                                                                                                                                         
INFO on line: "483" in file: "src/pkcs11.c": return "C_FindObjectsInit" value: 0                                                                                                                               
INFO on line: "487" in file: "src/pkcs11.c": enter "C_FindObjects"                                                                                                                                             
INFO on line: "487" in file: "src/pkcs11.c": return "C_FindObjects" value: 0                                                                                                                                   
INFO on line: "487" in file: "src/pkcs11.c": enter "C_FindObjects"                                                                                                                                             
INFO on line: "487" in file: "src/pkcs11.c": return "C_FindObjects" value: 0
INFO on line: "491" in file: "src/pkcs11.c": enter "C_FindObjectsFinal"                                                                                                                                        
INFO on line: "491" in file: "src/pkcs11.c": return "C_FindObjectsFinal" value: 0                                                                                                                              
INFO on line: "475" in file: "src/pkcs11.c": enter "C_GetAttributeValue"                                                                                                                                       
INFO on line: "475" in file: "src/pkcs11.c": return "C_GetAttributeValue" value: 0                                                                                                                             
INFO on line: "475" in file: "src/pkcs11.c": enter "C_GetAttributeValue"                                                                                                                                       
INFO on line: "475" in file: "src/pkcs11.c": return "C_GetAttributeValue" value: 0                                                                                                                             
Wed Aug 19 10:12:26 2020 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Aug 19 10:12:26 2020 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
Wed Aug 19 10:12:26 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:1194                                                                                                             
Wed Aug 19 10:12:26 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]                                                                                                                                 
Wed Aug 19 10:12:26 2020 UDP link local: (not bound)                                                   
Wed Aug 19 10:12:26 2020 UDP link remote: [AF_INET]127.0.0.1:1194                                                                                                                                              
Wed Aug 19 10:12:26 2020 TLS: Initial packet from [AF_INET]127.0.0.1:1194, sid=1d911c51 750184cf                                                                                                               
Wed Aug 19 10:12:26 2020 VERIFY OK: depth=1, CN=Easy-RSA CA                                                                                                                                                    
Wed Aug 19 10:12:26 2020 VERIFY KU OK                                                                  
Wed Aug 19 10:12:26 2020 Validating certificate extended key usage                                                                                                                                             
Wed Aug 19 10:12:26 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
Wed Aug 19 10:12:26 2020 VERIFY EKU OK                                                                 
Wed Aug 19 10:12:26 2020 VERIFY OK: depth=0, CN=server                                                 
Wed Aug 19 10:12:26 2020 OpenSSL: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib                                                                                                                
Wed Aug 19 10:12:26 2020 TLS_ERROR: BIO read tls_read_plaintext error                                                                                                                                          
Wed Aug 19 10:12:26 2020 TLS Error: TLS object -> incoming plaintext read error                                                                                                                                
Wed Aug 19 10:12:26 2020 TLS Error: TLS handshake failed                                               
Wed Aug 19 10:12:26 2020 SIGUSR1[soft,tls-error] received, process restarting                                                                                                                                  
Wed Aug 19 10:12:26 2020 Restart pause, 5 second(s)                                                    
^CWed Aug 19 10:12:30 2020 SIGINT[hard,init_instance] received, process exiting                                                                                                                                
INFO on line: "379" in file: "src/pkcs11.c": enter "C_Finalize"                                                                                                                                                
INFO on line: "76" in file: "src/lib/backend.c": Destroying backends                                                                                                                                           
INFO on line: "77" in file: "src/lib/backend_fapi.c": Calling Fapi_Finalize                                                                                                                                    
INFO on line: "379" in file: "src/pkcs11.c": return "C_Finalize" value: 0
```

**Comment by williamcroberts** [comment]
> ```shell
> Wed Aug 19 10:12:26 2020 VERIFY KU OK                                                                  
> Wed Aug 19 10:12:26 2020 Validating certificate extended key usage                                                                                                                                             
> Wed Aug 19 10:12:26 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> Wed Aug 19 10:12:26 2020 VERIFY EKU OK                                                                 
> Wed Aug 19 10:12:26 2020 VERIFY OK: depth=0, CN=server                                                 
> Wed Aug 19 10:12:26 2020 OpenSSL: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib                                                                                                                
> Wed Aug 19 10:12:26 2020 TLS_ERROR: BIO read tls_read_plaintext error                                                                                                                                          
> Wed Aug 19 10:12:26 2020 TLS Error: TLS object -> incoming plaintext read error                                                                                                                                
> Wed Aug 19 10:12:26 2020 TLS Error: TLS handshake failed                                               
> Wed Aug 19 10:12:26 2020 SIGUSR1[soft,tls-error] received, process restarting                                                                                                                                  
> Wed Aug 19 10:12:26 2020 Restart pause, 5 second(s)                                                    
> ^CWed Aug 19 10:12:30 2020 SIGINT[hard,init_instance] received, process exiting   
> ```

hrm I wish I could spot the error, I don't see it sending any weirdness back via PKCS11 interface, perhaps its  getting an attribute value that is the public key bits and something is wrong there?

**Comment by williamcroberts** [comment]
> > ```shell
> > Wed Aug 19 10:12:26 2020 VERIFY KU OK                                                                  
> > Wed Aug 19 10:12:26 2020 Validating certificate extended key usage                                                                                                                                             
> > Wed Aug 19 10:12:26 2020 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> > Wed Aug 19 10:12:26 2020 VERIFY EKU OK                                                                 
> > Wed Aug 19 10:12:26 2020 VERIFY OK: depth=0, CN=server                                                 
> > Wed Aug 19 10:12:26 2020 OpenSSL: error:141F0006:SSL routines:tls_construct_cert_verify:EVP lib                                                                                                                
> > Wed Aug 19 10:12:26 2020 TLS_ERROR: BIO read tls_read_plaintext error                                                                                                                                          
> > Wed Aug 19 10:12:26 2020 TLS Error: TLS object -> incoming plaintext read error                                                                                                                                
> > Wed Aug 19 10:12:26 2020 TLS Error: TLS handshake failed                                               
> > Wed Aug 19 10:12:26 2020 SIGUSR1[soft,tls-error] received, process restarting                                                                                                                                  
> > Wed Aug 19 10:12:26 2020 Restart pause, 5 second(s)                                                    
> > ^CWed Aug 19 10:12:30 2020 SIGINT[hard,init_instance] received, process exiting   
> > ```
> 
> hrm I wish I could spot the error, I don't see it sending any weirdness back via PKCS11 interface, perhaps its getting an attribute value that is the public key bits and something is wrong there?

@dnolover I wonder why don't we see CKR_MECHANISM_INVALID in this printout?

**Comment by dnoliver** [comment]
Because I did not set --verb 11 in that one, so we can see the TPM2_PKCS11 output. Otherwise I get a loooot of output (openvpn pkcs11 debug out is only seen in verb=11)

**Comment by williamcroberts** [comment]
> Because I did not set --verb 11 in that one, so we can see the TPM2_PKCS11 output. Otherwise I get a loooot of output (openvpn pkcs11 debug out is only seen in verb=11)

We should see something like an INFO line for the trace on the pkcs11 interface, we don't even see that.

**Pull request merged**
