### PR TITLE
Added importrsa key command to tpm2_ptool and updated test script

### PR DESCRIPTION
**Pull request by ichetty**
I also had to make a few changes to the tool and test script to support discrete tpm.
There a corresponding pr in the tpm2-tools repo https://github.com/tpm2-software/tpm2-tools/pull/1221

### CODE REVIEW

**Comment by williamcroberts** [comment]
@ichetty all your PRs are failing make check. You'll need to fix the breaks as well.

**Comment by williamcroberts** [comment]
@ichetty should this be closed? PR #64 is newer and has the same title.

**Comment by ichetty** [comment]
#1226 was for tpm2-tools and this one #64 is for the tpm2-pkcs11 is a redo of #60 & #61

**Comment by ichetty** [comment]
Closing this one as i have submitted another new PR

**Pull request closed without merging**
