### PR TITLE
add support for key labels and empty template find object calls

### PR DESCRIPTION
**Pull request by williamcroberts**
Peter Huewe (1):
      C_FindObjectsInit: Return all objects if ulCount is 0

William Roberts (2):
      tpm2_ptool.py: fix addtertiary variable name
      db: add support for key labels

### CODE REVIEW

**Comment by PeterHuewe** [comment]
*Ass* Support? Maybe you want to correct that typo :)

**Comment by williamcroberts** [comment]
> _Ass_ Support? Maybe you want to correct that typo :)

The major design flaw of the qwerty keyboard

**Comment by williamcroberts** [comment]
> _There_

Got those fixups for both patches

**Comment by PeterHuewe** [comment]
Looks good to me.

**Pull request merged**
