### PR TITLE
ci: test with Python 2 and Python 3

### PR DESCRIPTION
**Pull request by diabonas**
Since there have been some breakages with Python 3, add separate jobs for Python 2 and 3 to test that `tpm2_ptool` works with both versions. The Python 3 jobs will currently fail until #119 is merged.

### CODE REVIEW

**Comment by diabonas** [comment]
Unfortunately the Docker image doesn't seem to have Python 3 installed, as the [error message for the Python 3 jobs is](https://travis-ci.org/tpm2-software/tpm2-pkcs11/jobs/486957186#L2511)
```
/workspace/tpm2-pkcs11/build/../tools/tpm2_ptool: line 2: python3: command not found
```
This would need to be installed first for this PR to make sense.

**Comment by williamcroberts** [comment]
Done ill do it and post back, can you rebase the PR on tip of master

**Comment by diabonas** [comment]
Wow, that was quick, thank you very much! :smiley: That seems to have worked, but we now need `python3-yaml`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 7, in <module>
    from .commandlets_store import InitCommand  # pylint: disable=unused-import
  File "/workspace/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_store.py", line 6, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by diabonas** [comment]
(And probably `python3-cryptography` as well.)

**Comment by williamcroberts** [comment]
@diabonas thanks, I was wondering what package it was going to be. Doing it now and running the CI tests locally. Ill push to docker and re-trigger when done. Thanks.

**Pull request merged**
